In [9]:
import pandas as pd
import numpy as np

In [10]:
dataset = pd.read_csv('CAA_NRC REFINED DATA with polarity.csv')

In [11]:
# Creating the bag of words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform((dataset['tweet_lemmatized'].values).astype('U')).toarray()


y = dataset['polarity'].values

# Splitting in Train and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 929   14   17]
 [  45 1136   66]
 [  23   16  544]]


In [12]:
total_tweets_in_testset = np.sum(cm)
correct_predictions = cm[0,0] + cm[1,1] + cm[2,2]
accuracy = (correct_predictions/total_tweets_in_testset)*100
print(accuracy)

93.51254480286738
